### PR TITLE
Add Lucene Document parameter to factory Func 

### PR DESCRIPTION
**Pull request by mcintyre321**
I want to be able to look up objects without having to instantiate a second copy. To this end I have changed the factory delegate to Func<Document, T>.

I think perhaps this would be better as part of the IDocumentMapper, with T CreateObject(..) rather than void ToObject(...), but given that the factory is separate, the way I have done it is idiomatic with the current design.

### CODE REVIEW

**Comment by chriseldredge** [comment]
When retrieving objects from a session, the engine explicitly creates duplicate objects in order to be able to determine if any objects are dirty when the session is committed. This change would cause that strategy to never detect changes since it would be comparing objects to themselves.

As the index changes and gets reloaded I can see pitfalls here with the Func<T> delegate not having its cache invalidated properly.

Are your objects expensive to construct or is there some other benefit to avoiding creating the duplicates? In the limited cpu profiling I've done this hasn't been an area of significant computation relative to the rest of the library.

**Comment by mcintyre321** [comment]
The objects I am querying on are passed a reference to their parent object in their constructor, which I don't want to attach extra children to, nor do I want to create an extra constructor without parameters, really... 

Perhaps DetermineDirty method\* could be overrideable - there are various strategies for determining if an object has changed (e.g. listening to INotifyPropertyChanged, which might be more performant than iterating over the objects to see which ones don't match)

*if such a thing exists!

**Comment by mcintyre321** [comment]
It looks like the SessionDocumentTracker could have an interface extracted, and be injected into the LuceneSession. I could then implement this myself.

**Comment by chriseldredge** [comment]
I agree the current method is not the most efficient, but it is the most likely to work in the general case where entities do not implement INotifyPropertyChanged.

If you are willing to extract that into an interface and make the related changes (with unit tests) then I would be more comfortable with the original PR.

**Pull request closed without merging**
