### PR TITLE
DateTime/DateTimeOffset bug

### PR DESCRIPTION
**Pull request by mcintyre321**
I've added a couple of tests that fail when sorting on DateTime/DateTimeOffsets. I'm not really sure why, but the dates, when retrieved as strings don't match the format, so ParseExact fails.

I'll keep looking and see if I can get to the bottom of why this is, but I might get lost!

### CODE REVIEW

**Comment by mcintyre321** [comment]
I've run into the limits of my Lucene knowledge :(

**Comment by chriseldredge** [comment]
Thanks for the report and the tests. I'll see if I can figure out what's going on. In the meantime, you could either mark the property as [NumericField] or provide your own TypeConverter to work around the problem.

**Comment by chriseldredge** [comment]
Yes, numeric fields should support range queries. If not, that’s another bug. :)

**Comment by mcintyre321** [comment]
So I've found a fix - there is a class called DateTools inside Lucene which formats dates correctly, there is an updated version of the DateTimeConverter here https://gist.github.com/mcintyre321/5876578.

Adding this breaks a few tests around the existing DateTime converter, but I think it's probably more 'correct', and the OrderByTests.cs covers it with integration tests.

I hesitate to send a pull request, as I suspect some code will be required to read values stored in indexes using the old format will be needed...

```
if (Settings.UseOlderDateFormat) 
{
//use old method
}else{
//use DateTools from Gist
}
```

What do you think? It's always tricky where saved data is involved!

**Comment by chriseldredge** [comment]
After some investigation, the problem is that the field needs to be either indexed without analysis:

```
[Field(IndexMode.NotAnalyzed)]
public DateTime DateTime { get; set; }
```

Or alternatively it needs to be analyzed with a KeywordAnalyzer

```
[Field(Analyzer = typeof(KeywordAnalyzer))]
public DateTime DateTime { get; set; }
```

Note that the 2nd approach only works if you are not passing your own Analyzer into the <tt>LuceneDataProvider</tt> constructor. If you are providing your own Analyzer, it would need to use KeywordAnalyzer for the fields you want to order by or query by.

The tests would pass after either approach except for a time zone mismatch.

DateTools sounds intuitive, but my DateTimeConverter supports arbitrary formats, which IMO is better than forcing a "standard" format on people. Incidentally, the default format is compatible with Solr's date format. If you want to choose your own format you can do so:

```
[Field(Format = "yyyyMMddHHmmssfff")]
public DateTime DateTime { get; set; }
```

This format neatly sidesteps the analyzer issue since it won't be tokenized by StandardAnalyzer.

Finally, when you are creating new indexes and can choose the format, I would recommend using NumericField for these, since in theory it should result in smaller indexes and better performance.

**Comment by mcintyre321** [comment]
From the point of view of a library consumer, it would be best if the out-of-the box format didn't throw exceptions under certain sorting conditions... Is there going to be a fix for thator will I have to provide my own format/override/attributes?

**Comment by chriseldredge** [comment]
That's valid. I was thinking it might work if you don't provide an external analyzer, but it does not.

**Comment by chriseldredge** [comment]
Traced the problem to FieldMappingInfoBuilder treating the field as case insensitive causing the analyzer to convert the text to lower case. Fixed in 27bfaa4805dec325ac9e39254072e74e17f89592. I'll close this issue after releasing to nuget.org.

**Comment by mcintyre321** [comment]
Great, thanks!

sent from my mobile

**Comment by chriseldredge** [comment]
Released in 3.1.51 (https://nuget.org/packages/Lucene.Net.Linq/3.1.51)

**Pull request closed without merging**
