### PR TITLE
Made method virtual allowing custom IDocumentKey creation

### PR DESCRIPTION
**Pull request by mcintyre321**
I made a property on DocumentMapperBase virtual so that I can implement my own IDocumentKey type for custom object loading.

### CODE REVIEW

**Comment by mcintyre321** [comment]
Any chance of having this merged and pushed up? As far as I can tell this is just correcting a mistake (that the properties on this class which create IDocumentKeys should be virtual so that custom implementation can be used).

**Comment by chriseldredge** [comment]
This looks like a step in the right direction, but subclasses that want to override `ToKey` may want to make use of `ValidateKey` which is currently private. What do you think about changing `ValidateKey` to `protected virtual` as well?

**Comment by mcintyre321** [comment]
I did that initially then undid it in case it made the PR less likely to
get accepted!

I can add it back in if you like. :)

**Comment by mcintyre321** [comment]
Done!

**Comment by mcintyre321** [comment]
Could you push a new Nuget package please? thanks again

**Comment by chriseldredge** [comment]
3.6.0 was just pushed to nuget.org with this change.

**Pull request merged**
